# Generated by Django 5.0.3 on 2024-09-08 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='custom_user',
        ),
    ]
