# Generated by Django 5.0.3 on 2024-08-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='delivery_adresse',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
