<<<<<<< HEAD
# Generated by Django 5.0.3 on 2024-08-27 09:35
=======
# Generated by Django 5.0.3 on 2024-09-08 18:24
>>>>>>> 9a3759cac4f1c7f7ad2d8594f681cc397deb39e6

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_coupons', to='shop.shop'),
        ),
    ]
