# Generated by Django 5.0.3 on 2024-04-01 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_role_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Rôle'},
        ),
    ]
