# Generated by Django 5.0.7 on 2024-08-24 11:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_role_options'),
        ('shop', '0015_order_address_order_coupon_code_order_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coupon_code', models.CharField(max_length=50)),
                ('nombre_activation', models.IntegerField(default=0)),
                ('max_activation', models.IntegerField(default=1)),
                ('reduction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_publish', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_coupons', to='shop.shop')),
            ],
        ),
    ]
