<<<<<<< HEAD
# Generated by Django 5.0.3 on 2024-08-27 09:35
=======
# Generated by Django 5.0.3 on 2024-09-08 18:24
>>>>>>> 9a3759cac4f1c7f7ad2d8594f681cc397deb39e6

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
        migrations.AddField(
<<<<<<< HEAD
            model_name='campaign',
            name='target_products',
            field=models.ManyToManyField(to='shop.product'),
        ),
        migrations.AddField(
=======
>>>>>>> 9a3759cac4f1c7f7ad2d8594f681cc397deb39e6
            model_name='productreview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.product'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shop',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.shop'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shop.shop'),
        ),
        migrations.AddField(
<<<<<<< HEAD
            model_name='campaign',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='shop.shop'),
        ),
        migrations.AddField(
            model_name='shopcategorie',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_categorie', to='shop.category'),
        ),
        migrations.AddField(
            model_name='shopcategorie',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.shop'),
        ),
        migrations.AddField(
=======
>>>>>>> 9a3759cac4f1c7f7ad2d8594f681cc397deb39e6
            model_name='shopreview',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop'),
        ),
        migrations.AddField(
            model_name='shopreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
<<<<<<< HEAD
            model_name='subscribershop',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='shop.shop'),
        ),
        migrations.AddField(
            model_name='subscribershop',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shop',
            name='subscription',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.subscription'),
=======
            model_name='subscription',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='shop.shop'),
>>>>>>> 9a3759cac4f1c7f7ad2d8594f681cc397deb39e6
        ),
        migrations.AddField(
            model_name='subscriptionhistory',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop'),
        ),
        migrations.AddField(
            model_name='subscriptionhistory',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.subscription'),
        ),
<<<<<<< HEAD
        migrations.AlterUniqueTogether(
            name='shopcategorie',
            unique_together={('category', 'shop')},
        ),
        migrations.AlterUniqueTogether(
            name='subscribershop',
            unique_together={('user', 'shop')},
        ),
=======
>>>>>>> 9a3759cac4f1c7f7ad2d8594f681cc397deb39e6
    ]
