# Generated by Django 5.0.3 on 2024-06-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity_in_stock',
            field=models.IntegerField(default=0),
        ),
    ]
