name: Deploy to PythonAnywhere
on:
  push:
    branches:
      - main  # Remplacez par le nom de votre branche de déploiement

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10  # Remplacez par la version de Python que vous utilisez

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt


    - name: Deploy to PythonAnywhere
      run: |
        pip install pythonanywhere
        pa_autoconfigure_django.py --nuke ${{ secrets.PYTHONANYWHERE_API_TOKEN }} https://github.com/username/repo.git
      env:
        PYTHONANYWHERE_API_TOKEN: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
       
