name: Déployer Django sur PythonAnywhere

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Extraire le code
        uses: actions/checkout@v3

      - name: Configurer SSH
        run: ssh-keyscan -t rsa git@api.pythonanywhere.com >> ~/.ssh/known_hosts

      - name: Déployer le code
        run: |
          git push -f git@api.pythonanywhere.com:djassa2baby/djassa2baby.git main
          source .env
          pythonanywhere --ctl djassa2baby update

