name: Deploy to PythonAnywhere
on:
  push:
    branches:
      - main  # Remplacez par le nom de votre branche de déploiement

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to PythonAnywhere
      run: |
        pip install pythonanywhere
        pa_autoconfigure_django.py https://github.com/kabdoullah/djassa2baby.git [--branch=main --domain=djassa2baby.pythonanywhere.com --python=3.10] [--nuke ${{ secrets.PYTHONANYWHERE_API_TOKEN }}]
      env:
        PYTHONANYWHERE_API_TOKEN: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
       
